config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :group_chats, only: [:new, :create, :show, :index]
  root 'group_chats#index'

  mount ActionCable.server => '/cable'
end

app/models/group_chat.rb
class GroupChat < ActiveRecord::Base
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}
  belongs_to :user
  belongs_to :group_chat

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :group_chat, dependent: :destroy
  has_many :messages, dependent: :destroy

  def name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/group_chats_controller.rb
class GroupChatsController < ApplicationController
  def index
    @group_chat = GroupChat.all
  end

  def new
    @group_chat = GroupChat.new
  end

  def create
    @group_chat = current_user.group_chat.build(group_chat_params)

    if @group_chat.save
      flash[:success] = 'Group added added!'
      redirect_to group_chats_path
    else
      render 'new'
    end
  end

  def show
    @group_chat = GroupChat.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  private

  def group_chat_params
    params.require(:group_chat).permit(:title)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end
end

app/views/group_chats/_group_chat.html.haml
%a.list-group-item{href: group_chat_path(group_chat)}
  - last_message = group_chat.messages.last
  %h3.list-group-item-heading=group_chat.title
  %h5.list-group-item-heading
    -if last_message
      = last_message.user.name
  %p.list-group-item-text
    - if last_message
      =last_message.body
  %span.tag.tag-info
    - if last_message
      =last_message.created_at.to_formatted_s(:short)

app/views/group_chats/index.html.haml
%ul.list-group
  = render @group_chat

app/views/group_chats/new.html.haml
%h1 Add new group
.form-inline
  = form_for @group_chat do |f|
    .form-group
      .input-group
        .input-group-addon
          = f.label :title
        = f.text_field :title, autofocus: true, class: 'form-control'
    = f.submit 'Add!', class: 'btn btn-primary'

app/views/group_chats/show.html.haml
%h1= @group_chat.title
#messages{"data-group-chat-id" => "#{@group_chat.id}"}
  = render @group_chat.messages
%hr/

= form_for @message, url: '#' do |f|
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control'
    %small.text-muted From 2 to 1000 characters
  = f.submit "Post", class: 'btn btn-primary btn-lg'

app/views/layouts/_navigation.html.haml
.container
  // Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{"data-target" => "#nav-bar-colapsable-nav", "data-toggle" => "collapse", :type => "button"}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{href: "#{}"} Chat Machine

  / Collect the nav links, forms, and other content for toggling
  #nav-bar-colapsable-nav.collapse.navbar-collapse
    - if current_user
      %ul.nav.navbar-nav
        %li.nav-item
          = link_to 'Create new group', new_group_chat_path
        %li.nav-item
          = link_to "Home", group_chats_path
        %li.nav-item
          %a{href: "#{}"} Contact
        %li.nav-item
          %a{:href => "#"} About
        %li.nav-item.dropdown
          %a#responsiveNavbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#"}= gravatar_for current_user
          .dropdown-menu{"aria-labelledby" => "responsiveNavbarDropdown"}
            .dropdown-item
              = link_to "Sign out", destroy_user_session_path, method: :delete, id: "sign_out"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Chat Machine
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = action_cable_meta_tag
  %body#page-top
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      = render 'layouts/navigation'
    .body-container
      = yield

app/views/messages/_message.html.haml
%li.list-group-item.list-group-item-action
  .gravatar
    = gravatar_for message.user
  .message-body
    %h3.list-group-item-heading= message.user.name
    %p.list-group-item-text= message.body